
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 70
#define YY_END_OF_BUFFER 71
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[235] =
    {   0,
        0,    0,    0,    0,    0,    0,   71,   70,   69,   70,
       70,   36,   37,   33,   31,   40,   39,   56,   56,   42,
       38,   30,   41,   30,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   43,   44,   70,   47,   48,   49,   50,    0,   54,
        0,    0,    0,    0,   46,   68,   61,    0,    0,    0,
        0,   56,    0,   45,   30,   55,   55,   55,    0,   55,
       55,   55,   55,   55,   22,   55,   55,   55,   55,   18,
       35,   55,   55,    6,   32,   55,   55,   55,   55,   25,
       55,   55,   55,   55,   55,   55,   55,   48,    0,   52,

       51,    0,    0,    0,   61,    0,    0,   57,    0,   58,
       67,    0,   62,   62,   33,   55,   55,   55,   55,   55,
       33,   55,   55,   17,   23,   55,   55,   33,   34,   55,
       55,   55,    5,   55,   55,   55,    8,   55,   55,   55,
        0,   54,    0,   53,    0,   68,   68,    0,   61,   61,
       67,   59,    0,   57,   67,   60,    0,   58,   62,   55,
       55,   55,   15,   55,   55,   20,   55,   55,   55,   55,
       55,   27,   13,   55,   19,   29,    3,   55,   26,   55,
        0,   68,   61,    0,   59,   59,   65,   59,    0,   60,
       60,   66,   63,    4,   16,   55,    2,   55,   55,   55,

       55,   55,   55,   55,   21,   28,   59,    0,   59,   59,
       60,    0,   64,   63,   55,   24,   55,   55,   55,   55,
       55,    7,   59,   64,   14,    9,   55,   12,   55,    1,
       10,   55,   11,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    3,    4,    3,    3,    3,    3,    5,    6,
        7,    8,    9,   10,   11,   12,   13,   14,   15,   16,
       16,   16,   16,   16,   16,   16,   16,   17,   18,   19,
       20,   21,    3,    3,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   31,   32,   33,   34,   35,   36,
       31,   37,   38,   39,   40,   41,   42,   31,   43,   31,
       44,   45,   46,   47,   48,    3,   49,   50,   51,   52,

       53,   54,   55,   56,   57,   31,   31,   58,   59,   60,
       61,   62,   31,   63,   64,   65,   66,   67,   68,   31,
       69,   31,   70,    3,   71,    3,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[72] =
    {   0,
        1,    2,    3,    3,    4,    3,    3,    3,    3,    3,
        3,    5,    3,    6,    7,    7,    3,    3,    3,    3,
        3,    8,    9,    8,    8,    8,    9,   10,   10,   10,
       10,   10,   10,   11,   10,   10,   11,   10,   11,   10,
       11,   10,   10,    3,    3,    3,    3,   12,    8,    9,
        8,    8,    8,    9,   10,   10,   10,   10,   10,   11,
       10,   10,   11,   10,   11,   10,   11,   10,   10,    3,
       13
    } ;

static const flex_int16_t yy_base[254] =
    {   0,
        0,    0,   70,   71,    0,    0,  727,  728,  728,   70,
      140,  728,  728,  728,  728,  728,   63,   64,   68,  706,
      728,   65,  728,  654,   62,   55,   63,   70,   75,  128,
      623,  143,   56,   78,  127,   92,  130,  145,  170,  147,
      171,  728,  728,    0,  728,    0,  728,  728,   85,   91,
      169,  664,  663,  662,  728,  206,  209,  151,  122,  654,
      222,  228,  236,  728,  728,  606,  154,  167,  544,  201,
      213,  219,  212,  216,   64,  215,  230,  221,  232,  543,
      237,  245,  238,  539,  536,  240,  265,  252,  270,  535,
      258,  259,  257,  274,  260,  279,  534,    0,   93,  728,

      728,  576,  296,  319,  323,  331,   87,  329,  566,  567,
      336,  339,  728,  342,  530,  326,  329,  332,  324,  330,
      528,  331,  340,  525,  350,  349,  355,  524,  521,  371,
      377,  335,  519,  367,  358,  359,  495,  372,  376,  375,
      315,  322,  406,  728,  422,  728,  427,  430,  728,  433,
      402,  419,  440,  444,  506,    0,  475,  472,  446,  409,
      416,  437,  425,  426,  427,  383,  445,  431,  440,  451,
      434,  334,  323,  435,  321,  315,  284,  454,  281,  455,
      424,  495,  498,  472,  486,  491,  501,  503,  301,    0,
        0,  276,    0,  225,  223,  497,  217,  486,  485,  493,

      501,  503,  504,  510,  169,  164,  510,  515,  517,  522,
        0,  195,    0,    0,  508,  144,  513,  509,  523,  373,
      526,  134,  525,    0,  132,  126,  529,  124,  527,  114,
       80,  540,   40,  728,  593,  606,  617,  628,  636,  641,
      652,  661,  668,  675,  683,  688,  692,  696,  700,  704,
      708,  712,  716
    } ;

static const flex_int16_t yy_def[254] =
    {   0,
      234,    1,  235,  235,  236,  236,  234,  234,  234,  237,
      238,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  234,  234,  240,  234,  241,  234,  234,  237,  237,
      237,  234,  234,  242,  234,  234,  234,  234,  234,  243,
      234,  234,  234,  234,  234,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  241,  244,  234,

      234,  234,  234,  234,  234,  234,  234,  234,  245,  246,
      234,  234,  234,  234,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      244,  244,  244,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  247,  248,  249,  246,  234,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      244,  234,  234,  234,  234,  234,  234,  234,  247,  250,
      248,  251,  252,  239,  239,  239,  239,  239,  239,  239,

      239,  239,  239,  239,  239,  239,  234,  234,  234,  234,
      250,  251,  253,  252,  239,  239,  239,  239,  239,  239,
      239,  239,  234,  253,  239,  239,  239,  239,  239,  239,
      239,  239,  239,    0,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234
    } ;

static const flex_int16_t yy_nxt[800] =
    {   0,
        8,    9,    8,   10,   11,   12,   13,   14,   15,   16,
       15,   17,   14,   18,   19,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   31,   32,
       31,   31,   33,   34,   35,   36,   37,   38,   39,   31,
       40,   41,   31,   42,    8,   43,    8,   44,   25,   26,
       27,   28,   29,   30,   31,   31,   32,   31,   33,   34,
       35,   36,   37,   38,   39,   31,   40,   41,   31,   45,
        8,   47,   47,   50,   55,   58,   56,   57,   57,   61,
       70,   62,   62,   62,   65,   65,   59,   69,   50,   71,
       82,   72,   60,   63,   50,   67,  142,   73,   68,   74,

      151,  152,   69,   69,   75,  122,   76,   70,   77,   69,
       69,   69,   83,   59,   51,   71,   82,   69,   72,   60,
       63,   67,   69,   73,   68,   69,   74,   69,   86,   51,
       75,  122,   76,  107,   77,   51,  108,  143,   83,   69,
       48,   48,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   84,   86,   87,   52,   52,   52,   52,
       52,   69,   78,   85,   56,   57,   57,   79,   93,   80,
       88,   69,   50,   69,   69,   69,   81,   69,  115,   69,
       84,   69,   87,   52,   54,   52,   52,   52,   78,   85,
       69,   69,   69,   79,   69,   93,   80,   88,   89,   94,

       95,   69,   81,  116,   90,  115,   91,   96,  212,   52,
       52,   69,   92,   51,   69,   99,   69,   69,   69,  103,
       57,   57,  105,  105,  105,   89,   94,   95,  117,  116,
       90,  104,   91,   96,  106,  111,   57,   57,   92,   61,
      119,   62,   62,   62,  112,  120,  112,  118,   69,  113,
      114,  114,  123,   63,  124,  117,  121,  125,  104,   69,
       69,  106,   69,   69,   69,  126,   69,  119,   69,  128,
       69,  120,   69,  118,  130,  127,  129,   69,  123,   69,
       63,  124,  121,  125,   69,   69,  131,   69,  132,  212,
      133,  126,   69,  137,  136,  134,  128,  135,  139,   69,

      130,  127,  129,  138,   69,   69,   69,   69,  140,  103,
       57,   57,   69,  131,  189,  132,  133,   69,  142,  137,
      136,   69,  134,  135,  139,  142,   69,  145,   69,  145,
      138,   69,  146,  147,  147,  140,  105,  105,  105,  148,
      153,  148,  154,  154,  149,  150,  150,  160,  106,  103,
       57,   57,  113,  114,  114,  159,  159,  159,  161,  143,
      163,  104,   69,  162,  165,  166,  143,  164,   69,  174,
       69,   69,  168,   69,  160,  106,   69,   69,   69,   69,
      169,   69,   69,  176,  177,  161,  163,   69,  104,  162,
      165,  167,  166,  164,  170,  174,   69,   69,  171,  168,

      175,  172,   69,  178,  179,   69,   69,  169,  173,  142,
      176,  177,  229,  180,   69,  184,  185,  167,   69,   69,
       69,  170,   69,   69,   69,  171,  175,  142,  172,  178,
       69,  179,  186,  186,  173,  146,  147,  147,  229,  180,
      182,  182,  182,  149,  150,  150,  183,  183,  183,  195,
      143,  194,  181,  187,  188,  153,   69,  154,  154,  159,
      159,  159,  196,   69,  197,  198,  199,  201,  143,  200,
      203,  204,   69,   69,   69,  195,  202,  194,   69,  205,
      206,   69,   69,  157,   69,  184,  185,   69,  192,  196,
      197,  198,   69,  199,  201,  200,  203,  204,   69,  207,

      207,   69,   69,  202,  186,  186,  205,  206,  182,  182,
      182,  183,  183,  183,  208,  209,  210,  210,  215,  189,
      216,  217,  218,  207,  207,  221,  219,  220,  208,  209,
      223,  223,   69,   69,  222,  210,  210,  226,  223,  223,
       69,  225,   69,  227,   69,  215,  216,  217,   69,  218,
       69,   69,  221,  219,  220,   69,   69,   69,  230,  228,
       69,  222,  231,  232,  226,  233,   69,  225,   69,  227,
       69,   69,   69,   69,   69,   69,   69,   69,  157,  155,
      144,   69,   69,   69,  230,  228,   69,   69,  231,  232,
       69,   69,  233,   46,   46,   46,   46,   46,   46,   46,

       46,   46,   46,   46,   46,   46,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   66,   66,   66,   66,   66,   66,   66,   97,   97,
       97,   97,   98,   69,   98,   98,   98,   98,   98,   98,
       98,   98,   98,   98,  102,  109,  100,  101,  100,  102,
       69,  102,  110,   65,  110,  110,  110,  141,  141,  141,
      141,  141,  141,  141,  141,  141,  141,  141,  156,  156,
      156,  156,  158,  158,  158,  158,  158,  190,  190,  190,

      190,  191,  191,  191,  191,  193,  193,  193,  193,  211,
      211,  211,  211,  213,  213,  213,  213,  214,  214,  214,
      214,  224,  224,  224,  224,   64,  234,    7,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234

    } ;

static const flex_int16_t yy_chk[800] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,   10,   17,   18,   17,   17,   17,   19,
       26,   19,   19,   19,   22,   22,   18,  233,   49,   26,
       33,   27,   18,   19,   50,   25,   99,   27,   25,   28,

      107,  107,   26,   33,   28,   75,   29,   26,   29,   25,
       27,   75,   34,   18,   10,   26,   33,   28,   27,   18,
       19,   25,   29,   27,   25,   34,   28,  231,   36,   49,
       28,   75,   29,   59,   29,   50,   59,   99,   34,   36,
        3,    4,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   35,   36,   37,   11,   11,   11,   11,
       11,  230,   30,   35,   58,   58,   58,   30,   40,   32,
       38,  228,   51,  226,   35,   30,   32,   37,   67,  225,
       35,  222,   37,   11,   11,   11,   11,   11,   30,   35,
       32,  216,   38,   30,   40,   40,   32,   38,   39,   41,

       41,   67,   32,   68,   39,   67,   39,   41,  212,   11,
       11,  206,   39,   51,   68,   51,  205,   39,   41,   56,
       56,   56,   57,   57,   57,   39,   41,   41,   70,   68,
       39,   56,   39,   41,   57,   61,   61,   61,   39,   62,
       72,   62,   62,   62,   63,   73,   63,   71,   70,   63,
       63,   63,   76,   62,   77,   70,   74,   78,   56,   73,
       71,   57,   76,   74,  197,   79,   72,   72,   78,   82,
      195,   73,  194,   71,   86,   81,   83,   77,   76,   79,
       62,   77,   74,   78,   81,   83,   87,   86,   87,  192,
       88,   79,   82,   93,   92,   89,   82,   91,   95,   88,

       86,   81,   83,   94,   93,   91,   92,   95,   96,  103,
      103,  103,   87,   87,  189,   87,   88,   89,  141,   93,
       92,   94,   89,   91,   95,  142,   96,  104,  179,  104,
       94,  177,  104,  104,  104,   96,  105,  105,  105,  106,
      108,  106,  108,  108,  106,  106,  106,  116,  105,  111,
      111,  111,  112,  112,  112,  114,  114,  114,  117,  141,
      119,  111,  176,  118,  122,  123,  142,  120,  175,  132,
      173,  119,  126,  116,  116,  105,  117,  120,  122,  118,
      127,  172,  132,  135,  136,  117,  119,  123,  111,  118,
      122,  125,  123,  120,  130,  132,  126,  125,  130,  126,

      134,  131,  127,  138,  139,  135,  136,  127,  131,  143,
      135,  136,  220,  140,  134,  151,  151,  125,  130,  138,
      220,  130,  140,  139,  131,  130,  134,  181,  131,  138,
      166,  139,  152,  152,  131,  145,  145,  145,  220,  140,
      147,  147,  147,  148,  148,  148,  150,  150,  150,  161,
      143,  160,  143,  153,  153,  154,  160,  154,  154,  159,
      159,  159,  162,  161,  164,  165,  167,  169,  181,  168,
      171,  174,  163,  164,  165,  161,  170,  160,  168,  178,
      180,  171,  174,  158,  162,  184,  184,  169,  157,  162,
      164,  165,  167,  167,  169,  168,  171,  174,  170,  185,

      185,  178,  180,  170,  186,  186,  178,  180,  182,  182,
      182,  183,  183,  183,  187,  187,  188,  188,  196,  155,
      198,  199,  200,  207,  207,  203,  201,  202,  208,  208,
      209,  209,  199,  198,  204,  210,  210,  217,  223,  223,
      200,  215,  137,  218,  196,  196,  198,  199,  201,  200,
      202,  203,  203,  201,  202,  215,  218,  204,  221,  219,
      217,  204,  227,  229,  217,  232,  133,  215,  129,  218,
      219,  128,  124,  221,  229,  121,  227,  115,  110,  109,
      102,   97,   90,   85,  221,  219,   84,  232,  227,  229,
       80,   69,  232,  235,  235,  235,  235,  235,  235,  235,

      235,  235,  235,  235,  235,  235,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  239,  239,  239,  239,  239,  239,  239,  240,  240,
      240,  240,  241,   66,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  242,   60,   54,   53,   52,  242,
       31,  242,  243,   24,  243,  243,  243,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  245,  245,
      245,  245,  246,  246,  246,  246,  246,  247,  247,  247,

      247,  248,  248,  248,  248,  249,  249,  249,  249,  250,
      250,  250,  250,  251,  251,  251,  251,  252,  252,  252,
      252,  253,  253,  253,  253,   20,    7,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#line 5 "lex.l"
#define T_EOF			0
#define T_PROGRAM		1
#define T_CONST			2
#define T_TYPE			3
#define T_ARRAY			4
#define T_SET			5
#define T_OF			6
#define T_RECORD		7
#define T_VAR			8
#define T_FORWARD		9
#define T_FUNCTION		10
#define T_PROCEDURE		11
#define T_INTEGER		12
#define T_REAL			13
#define T_BOOLEAN		14
#define T_CHAR			15
#define T_BEGIN			16
#define T_END			17
#define T_IF			18
#define T_THEN			19
#define T_ELSE			20
#define T_WHILE			21
#define T_DO			22
#define T_FOR			23
#define T_DOWNTO		24
#define T_TO			25
#define T_WITH			26
#define T_READ			27
#define T_WRITE			28
#define T_BCONST		29
#define T_RELOP			30
#define T_ADDOP			31
#define T_OROP			32
#define T_MULDIVANDOP	33
#define T_NOTOP			34
#define T_INOP			35
#define T_LPAREN		36
#define T_RPAREN		37
#define T_SEMI			38
#define T_DOT			39
#define T_COMMA			40
#define T_EQU			41
#define T_COLON			42
#define T_LBRACK		43
#define T_RBRACK		44
#define T_ASSIGN		45
#define T_DOTDOT		46
#define T_CCONST		47
#define T_ICONST		48
#define T_RCONST		49
#define T_ID			50
#define T_STRING		51


int lineno = 1;

void ERROR (const char msg []);
void Print_String(int token_id);
#line 763 "lex.yy.c"
 
/* mnimonika onomata (under construction) */
#line 766 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1
#define STRING 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 86 "lex.l"


#line 988 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 235 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 728 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 88 "lex.l"
{Print_String(T_PROGRAM); return T_PROGRAM;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 89 "lex.l"
{Print_String(T_CONST); return T_CONST;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 90 "lex.l"
{Print_String(T_TYPE); return T_TYPE;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 91 "lex.l"
{Print_String(T_ARRAY); return T_ARRAY;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 92 "lex.l"
{Print_String(T_SET); return T_SET;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 93 "lex.l"
{Print_String(T_OF); return T_OF;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 94 "lex.l"
{Print_String(T_RECORD); return T_RECORD;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 95 "lex.l"
{Print_String(T_VAR); return T_VAR;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 96 "lex.l"
{Print_String(T_FORWARD); return T_FORWARD;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 97 "lex.l"
{Print_String(T_FUNCTION); return T_FUNCTION;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 98 "lex.l"
{Print_String(T_PROCEDURE); return T_PROCEDURE;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 99 "lex.l"
{Print_String(T_INTEGER); return T_INTEGER;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 100 "lex.l"
{Print_String(T_REAL); return T_REAL;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 101 "lex.l"
{Print_String(T_BOOLEAN); return T_BOOLEAN;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 102 "lex.l"
{Print_String(T_CHAR); return T_CHAR;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 103 "lex.l"
{Print_String(T_BEGIN); return T_BEGIN;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 104 "lex.l"
{Print_String(T_END); return T_END;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 105 "lex.l"
{Print_String(T_IF); return T_IF;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 106 "lex.l"
{Print_String(T_THEN); return T_THEN;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 107 "lex.l"
{Print_String(T_ELSE); return T_ELSE;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 108 "lex.l"
{Print_String(T_WHILE); return T_WHILE;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 109 "lex.l"
{Print_String(T_DO); return T_DO;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 110 "lex.l"
{Print_String(T_FOR); return T_FOR;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 111 "lex.l"
{Print_String(T_DOWNTO); return T_DOWNTO;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 112 "lex.l"
{Print_String(T_TO); return T_TO;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 113 "lex.l"
{Print_String(T_WITH); return T_WITH;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 114 "lex.l"
{Print_String(T_READ); return T_READ;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 115 "lex.l"
{Print_String(T_WRITE); return T_WRITE;}
	YY_BREAK
case 29:
#line 118 "lex.l"
case 30:
YY_RULE_SETUP
#line 118 "lex.l"
{Print_String(T_RELOP); return T_RELOP;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 119 "lex.l"
{Print_String(T_ADDOP); return T_ADDOP;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 120 "lex.l"
{Print_String(T_OROP); return T_OROP;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 121 "lex.l"
{Print_String(T_MULDIVANDOP); return T_MULDIVANDOP;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 122 "lex.l"
{Print_String(T_NOTOP); return T_NOTOP;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 123 "lex.l"
{Print_String(T_INOP); return T_INOP;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 125 "lex.l"
{Print_String(T_LPAREN); return T_LPAREN;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 126 "lex.l"
{Print_String(T_RPAREN); return T_RPAREN;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 127 "lex.l"
{Print_String(T_SEMI); return T_SEMI;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 128 "lex.l"
{Print_String(T_DOT); return T_DOT;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 129 "lex.l"
{Print_String(T_COMMA); return T_COMMA;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 130 "lex.l"
{Print_String(T_EQU); return T_EQU;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 131 "lex.l"
{Print_String(T_COLON); return T_COLON;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 132 "lex.l"
{Print_String(T_LBRACK); return T_LBRACK;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 133 "lex.l"
{Print_String(T_RBRACK); return T_RBRACK;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 134 "lex.l"
{Print_String(T_ASSIGN); return T_ASSIGN;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 135 "lex.l"
{Print_String(T_DOTDOT); return T_DOTDOT;}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 137 "lex.l"
{Print_String(T_EOF); return T_EOF;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 141 "lex.l"
BEGIN(COMMENT);
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 142 "lex.l"
;
	YY_BREAK
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 143 "lex.l"
{lineno++;}
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 144 "lex.l"
{}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 145 "lex.l"
BEGIN(INITIAL);
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 149 "lex.l"
{Print_String(T_CCONST); return T_CCONST;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 150 "lex.l"
{Print_String(T_CCONST); return T_CCONST;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 151 "lex.l"
{Print_String(T_CCONST); return T_CCONST;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 153 "lex.l"
{Print_String(T_STRING); return T_STRING;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 155 "lex.l"
{Print_String(T_ID); return T_ID;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 157 "lex.l"
{Print_String(T_ICONST); return T_ICONST;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 158 "lex.l"
{Print_String(T_ICONST); return T_ICONST;}			
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 159 "lex.l"
{Print_String(T_ICONST); return T_ICONST;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 163 "lex.l"
{Print_String(T_RCONST); return T_RCONST;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 164 "lex.l"
{Print_String(T_RCONST); return T_RCONST;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 165 "lex.l"
{Print_String(T_RCONST); return T_RCONST;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 166 "lex.l"
{Print_String(T_RCONST); return T_RCONST;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 167 "lex.l"
{Print_String(T_RCONST); return T_RCONST;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 168 "lex.l"
{Print_String(T_RCONST); return T_RCONST;}
	YY_BREAK
case 65:
#line 170 "lex.l"
case 66:
#line 171 "lex.l"
case 67:
YY_RULE_SETUP
#line 171 "lex.l"
{Print_String(T_RCONST); return T_RCONST;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 172 "lex.l"
{Print_String(T_RCONST); return T_RCONST;}
	YY_BREAK
case 69:
/* rule 69 can match eol */
YY_RULE_SETUP
#line 176 "lex.l"
{lineno++;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 178 "lex.l"
ECHO;
	YY_BREAK
#line 1396 "lex.yy.c"
case YY_STATE_EOF(STRING):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 235 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 235 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 234);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 178 "lex.l"


int main() {
	int token;
	
	do {
		token = yylex();
	} while (token != T_EOF);
	
	return 0;
}

void ERROR (const char msg[]) {
		fprintf(stderr, "ERROR, line %d: %s\n", lineno, msg);
			exit(1);
}

void Print_String(int token) {
    //if(FLEX_DEBUG && SHOW_TOKENS)
        printf("TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d\n\n", yytext, token, lineno);
       
}


